export const playerInfo = {
  access_Token: {
    expire_at: '2024-03-31T23:59:59',
    token: '_access_token_here',
  },
  player: {
    id: 1,
    username: 'example_user',
    first_name: 'John',
    last_name: 'Doe',
    gender: 'male',
    land: 'USA',
    country: 'USA',
    register_country: 'USA',
    phone: '1234567890',
    email: 'example@example.com',
    address: '123 Street Name',
    city: 'City',
    postal_code: '12345',
    birthday: new Date('1990-01-01'),
    password: null,
    have_password: 1,
    real_balance: 1000,
    balance: 1000,
    total_bet: 0,
    total_win: 0,
    ggr: 0,
    total_deposit: 0,
    total_withdraw: 0,
    is_blocked: 0,
    is_added_inhouse: 0,
    email_verified: true,
    email_verified_at: new Date(),
    phone_verified: 1,
    address_verified: 1,
    had_first_deposit: 0,
    kyc_status: 'verified',
    kyc_reject_reason: null,
    address_proof_status: null,
    address_proof_reject_reason: null,
    lang: 'en',
    avatar: null,
    wallet_address: null,
    chat_blocked: 0,
    chat_blocked_till: null,
    is_chat_admin: 0,
    last_login_dt: new Date(),
    create_dt: new Date(),
    update_dt: new Date(),
    google_2fa_is_active: 0,
    google2fa_secret: null,
    wager: 0,
    registration_ip: null,
    last_login_ip: null,
    remember_token: null,
    deposit_count: 1,

    rank: {
      level: 1,
      progress: 0,
      rank: 'Beginner',
    },
  },
}
